sudo: required

language: php
php:
  - '7.0'

services:
  - mysql

before_script:
  - mysql -e 'create database api_test;'
  - cp app/config/parameters_travis.yml.dist app/config/parameters.yml
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install --dev
  - php app/console doctrine:schema:create --env=test
  - php app/console hautelook:fixtures:load

script:
  - phpunit --configuration ./app/phpunit.xml.dist --coverage-text