sudo: required

language: php
php:
  - '7.0'

services:
  - docker

before_script:
  - mysql -e 'create database api_test;'
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install --prefer-source --optimize-autoloader
  - composer install -n

script: phpunit -c app