sudo: required

language: php
php:
  - '5.6'
  - '7.0'

services:
  - docker

install:
- sh docker.sh

before_script:
  - "mkdir -p ~/.composer"
  - composer self-update
  - composer install --prefer-source --optimize-autoloader
  - composer install -n

script: phpunit -c app